// Command itemtags compacts Dragonfly's pinned vanilla item tag membership
// into the tab-separated table the protocol crate embeds.
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"os"
	"regexp"
	"sort"
	"strings"
)

const (
	sourceRepository = "hashimthearab/dragonfly"
	sourceCommit     = "3d29a693c54b8412a6a1c619f5b06bd8cb09a0e5"
	sourcePath       = "server/item/recipe/item_tags.json"
	sourceSHA256     = "4af255938ccb9617cb7d33f9d531e38e5f2cbfeda28dbaca80bcb6076350227d"
	maximumBytes     = 1 << 20
)

var identifier = regexp.MustCompile(`^[a-z0-9_.-]+:[a-z0-9_./-]+$`)

func main() {
	input := flag.String("in", "", "pinned item_tags.json")
	flag.Parse()
	if err := run(*input, os.Stdout); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(path string, output io.Writer) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	if len(data) > maximumBytes {
		return fmt.Errorf("%s exceeds %d bytes", path, maximumBytes)
	}
	digest := sha256.Sum256(data)
	if got := hex.EncodeToString(digest[:]); got != sourceSHA256 {
		return fmt.Errorf("%s sha256 %s, want %s", path, got, sourceSHA256)
	}
	table, err := compact(data)
	if err != nil {
		return err
	}
	_, err = io.WriteString(output, table)
	return err
}

func compact(data []byte) (string, error) {
	var tags map[string][]string
	if err := json.Unmarshal(data, &tags); err != nil {
		return "", err
	}
	names := make([]string, 0, len(tags))
	for tag := range tags {
		names = append(names, tag)
	}
	sort.Strings(names)
	var out strings.Builder
	fmt.Fprintf(&out, "# Generated by tools/registrygen/cmd/itemtags from %s@%s %s sha256=%s; do not edit.\n",
		sourceRepository, sourceCommit, sourcePath, sourceSHA256)
	for _, tag := range names {
		items := append([]string(nil), tags[tag]...)
		sort.Strings(items)
		if !identifier.MatchString(tag) {
			return "", fmt.Errorf("invalid tag %q", tag)
		}
		for index, item := range items {
			if !identifier.MatchString(item) || (index > 0 && items[index-1] == item) {
				return "", fmt.Errorf("tag %s has an invalid or duplicate item %q", tag, item)
			}
		}
		fmt.Fprintf(&out, "%s\t%s\n", tag, strings.Join(items, " "))
	}
	return out.String(), nil
}
